#!/bin/bash

unset PGSERVICE
unset PGUSER
mkdir -p result
echo "| Query  | Time |"
echo "| -----  | ---- |"
for i in {1..22}
do
for j in {1..3}
do
    psql tpch -qAXtf queries/$i.sql -o result/$i.$j ;
    elapse=$(cat result/$i.$j | grep Execution | grep -Eo '[0-9]*.[0-9]* ms') ;
    echo "$i,'${elapse}'";
done
done